#!/bin/bash
#Install powershell and apply powercli-core module
#This script is for ubuntu 18.04
#Source: https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7#ubuntu-1804
#Powercli: https://www.altaro.com/vmware/install-powercli-ubuntu-linux-18-04-lts/
 
# Go to downloads dir
cd ~/Downloads
 
# Download the Microsoft repository GPG keys
wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
 
# Register the Microsoft repository GPG keys
sudo dpkg -i packages-microsoft-prod.deb
 
# Delete GPGP keys file from downloads
sudo rm packages-microsoft-prod.deb
 
# Update the list of products
sudo apt-get update
 
# Enable the "universe" repositories
sudo add-apt-repository universe
 
# Install PowerShell
sudo apt-get install -y powershell && echo Powershell installed, to open powershell CLI use \"pwsh\"
 
echo "How to activate PowerCLI module:"
echo "pwsh"
echo "Install-Module -Name VMware.PowerCLI"
echo "Set-PowerCLIConfiguration -InvalidCertificateAction Ignore"
echo "To test is module works"
echo "Get-VICommand"
